development:
  address: "smtp.gmail.com"
  port: 587
  domain: "localhost:3000"
  authentication: "plain"
  user_name: ENV['SENDMAIL_USERNAME']
  password: ENV['SENDMAIL_PASSWORD']
  enable_starttls_auto: true
  
production:
  address: "smtp.mailgun.org"
  port: 587
  domain: 'heroku.com'
  authentication: "plain"
  user_name: ENV['SENDMAIL_USERNAME']
  password: ENV['SENDMAIL_PASSWORD']
  enable_starttls_auto: true
  